
image: alpine:latest

before_script:
    - echo "Initializing Environment"

stages:
    - build
    - test


MA1-test:
  script:
    - echo "Generic test script"
  stage: test
  tags:
    - linux
    - docker
