
image: alpine:latest

before_script:
    - echo "Initializing Environment"
    - apk add less util-linux pciutils usbutils coreutils binutils findutils grep gtest build-base gcc abuild binutils

stages:
    - build
    - test


MA1-test:
  script:
    - echo "Generic test script"
    - cd MA1
    - make test
  stage: test
  tags:
    - linux docker
