
image: alpine:latest

before_script:
    - echo "Initializing Environment" >> /dev/null
    - echo " This system uses Alpine Linux because it's small and efficient" >> /dev/null
    - echo " For info on Alpine Linux, go to alpinelinux.org" >> /dev/null
    - echo "http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
    - apk add --update --no-cache less util-linux pciutils usbutils coreutils binutils findutils grep gtest build-base gcc abuild binutils gtest-dev lcov >> /dev/null

stages:
    - build
    - test

# MA1 is the Hello World assignment
MA1-build:
  stage: build
  script:
    - cd MA1
    - make build
  allow_failure: true
  tags:
    - linux
    - docker

MA1-test:
  stage: test
  script:
    - cd MA1
    - make test
  tags:
    - linux
    - docker

MA1-coverage:
  stage: test
  script:
    - cd MA1
    - make coverage
  tags:
    - linux
    - docker
  artifacts:
    paths:
      - MA1/coverage_report

# MA2 is the Big Five assignment
MA2-BigFive-build:
  stage: build
  script:
    - cd MA2-BigFive
    - make build
  allow_failure: true
  tags:
    - linux
    - docker

MA2-BigFive-test:
  stage: test
  script:
    - cd MA2-BigFive
    - make test
  tags:
    - linux
    - docker
